services:
  server:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/server
      - node_modules:/server/node_modules
      - logs:/logs
    environment:
      - PORT:3000
      - MONGODB_URI:mongodb://mongo:27017/test

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

volumes:
  node_modules:
  logs:
  mongodb_data:
